name: Trigger Docker image update when yt-dlp is updated

on:
  schedule:
    - cron: "30 2 * * *" # Nightly at 2:30
  workflow_dispatch: # Allow running manually

env:
  OTHER_REPO: yt-dlp/yt-dlp
  WORKFLOW: docker.yml

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release from other repo
        id: other
        run: |
          DATA=$(curl -s https://api.github.com/repos/$OTHER_REPO/releases/latest)
          TAG=$(echo "$DATA" | jq -r .tag_name)
          DATE=$(echo "$DATA" | jq -r .published_at)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Get latest release from this repo
        id: ours
        run: |
          DATA=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          TAG=$(echo "$DATA" | jq -r .tag_name)
          DATE=$(echo "$DATA" | jq -r .published_at)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Run workflow for new release
        if: steps.other.outputs.date > steps.ours.outputs.date
        run: |
          echo "Detected newer release in $OTHER_REPO!"
          echo "Other repo tag: ${{ steps.other.outputs.tag }} (published ${{ steps.other.outputs.date }})"
          echo "Our repo tag:   ${{ steps.ours.outputs.tag }} (published ${{ steps.ours.outputs.date }})"

          gh workflow run "$WORKFLOW" --ref "${{ steps.ours.outputs.tag }}"
